name = "kwavemission"
pages_build_output_dir = "."
compatibility_date = "2026-08-15"

[[d1_databases]]
binding = "DB" # This must match the name used in your code
database_name = "kwavemission"
database_id = "019a1533-6e94-4b95-bca3-f4dec0772857"